#########################################################################
# Date: September 2024													
# Description: Code to set up PGI data and merge it with family relations
#########################################################################

module load R/4.2.2-foss-2022a-bare
R
library(dplyr)
library(data.table)

#######################################################################

## IMPORT RELEVANT DATASETS

# Load family relations from Lifelines
family <- read.table("/groups/umcg-lifelines/tmp01/projects/ov21_0226/dataset_order_202207/sec_family_relations/sec_family_relations.txt",header=TRUE, sep="\t")
family <- as.data.frame(family)

# Load all ids from Lifelines
all <- fread("/groups/umcg-lifelines/tmp01/projects/ov21_0226/dataset_order_202207/results/global_summary.csv", 
	sep=",", header=TRUE)
all <- as.data.frame(all)

# Select relevant variables and rename
all <- all %>%
	select(project_pseudo_id,date_of_birth,date_of_inclusion) %>%
	rename(id = project_pseudo_id)

# Reformat birthday variable for easier calculation in downstream analyses
all$year_of_birth <- as.numeric(substr(all$date_of_birth,1,4))
all$month_of_birth <- as.numeric(substr(all$date_of_birth,6,7))
	
print(nrow(all)) #169719
length(unique(all$id)) #169719

# Load ea_pgi from LifelinesPGIFile_sbayesV3 as generated by Sjoerd
ea_pgi <- fread("/groups/umcg-lifelines/tmp01/projects/ov21_0226/PGSpipelineV3/OUTPUT/LifelinesPGIFile_sbayesV3.csv", 
	sep=",", header=TRUE)
ea_pgi <- as.data.frame(ea_pgi)

print(nrow(ea_pgi)) #167781

# Select relevant variables and rename
ea_pgi <- ea_pgi %>%
	select(project_pseudo_id, EA4_Meta_PGI,
	EA4_Meta_Mother_PGI, EA4_Meta_Mother_PGI_Imp, EA4_Meta_Father_PGI, EA4_Meta_Father_PGI_Imp, 
	EA4_Meta_PGI_Parental,
	EA3NonCog_PGI, EA3Cog_PGI, 
	EA3NonCog_Mother_PGI, EA3NonCog_Mother_PGI_Imp, EA3NonCog_Father_PGI, EA3NonCog_Father_PGI_Imp, 
	EA3Cog_Mother_PGI, EA3Cog_Mother_PGI_Imp, EA3Cog_Father_PGI, EA3Cog_Father_PGI_Imp,
	EA3NonCog_PGI_Parental, EA3Cog_PGI_Parental,
	PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10)

#########################################################################

## TRIO FAMILY STRUCTURE

# Merge family structure based on id
parent <- merge(all, family, by.x="id", by.y="PROJECT_PSEUDO_ID")

# Rename and reformat variables
parent <- parent %>% 
	rename(mom_id = MOTHER_PROJECT_PSEUDO_ID,
	dad_id = FATHER_PROJECT_PSEUDO_ID,
	fam_id = FAM_ID,
	partner_id = PARTNER_PROJECT_PSEUDO_ID) %>% 
	mutate(mom_id = ifelse(mom_id == 0, NA, mom_id),
	dad_id = ifelse(dad_id == 0, NA, dad_id))

print(nrow(parent)) #167781
length(unique(parent$id)) #167781
any(duplicated(parent$id))  # FALSE
print(sum(complete.cases(parent$mom_id))) #80090
print(sum(complete.cases(parent$dad_id))) #80090

parent <- parent %>%
	filter(!is.na(mom_id)) %>%
	filter(!is.na(dad_id))
print(nrow(parent)) #80090

#######################################################################

## FURTHER INFORMATION ABOUT PARENTS 

# Number of children per parent
mom <- parent %>%
	group_by(mom_id) %>%
	summarise(n_child_m = n_distinct(id)) %>%
	ungroup()
dad <- parent %>%
	group_by(dad_id) %>%
	summarise(n_child_f = n_distinct(id)) %>%
	ungroup()
  
print(nrow(mom)) #44598
length(unique(mom$mom_id)) #44598
print(nrow(dad)) #44703
length(unique(dad$dad_id)) #44703

# Age of parent
mom <- merge(mom, all, by.x="mom_id",by.y="id", all.x=TRUE)
mom <- mom %>%
	rename(date_of_birth_m = date_of_birth,
	year_of_birth_m = year_of_birth,
	month_of_birth_m = month_of_birth) %>%
	select(-date_of_inclusion)
dad <- merge(dad, all, by.x="dad_id",by.y="id", all.x=TRUE)
dad <- dad %>%
	rename(date_of_birth_f = date_of_birth,
	year_of_birth_f = year_of_birth,
	month_of_birth_f = month_of_birth) %>%
	select(-date_of_inclusion)
	
# Merge this information back into the parent dataset
parent <- parent %>%
	left_join(mom, by = "mom_id") %>%
	left_join(dad, by = "dad_id")
		
# Calculate years_at_birth_m (maternal age at birth)
library(lubridate)

# Convert 'date_of_birth' (offspring) and 'date_of_birth_m' (mother) to Date objects
parent$date_of_birth <- ymd(paste0(parent$date_of_birth, "-01"))
parent$date_of_birth_m <- ymd(paste0(parent$date_of_birth_m, "-01"))
parent$date_of_birth_f <- ymd(paste0(parent$date_of_birth_f, "-01"))

# Calculate parents age at birth (years_at_birth_m)
parent$years_at_birth_m <- as.numeric(interval(parent$date_of_birth_m, parent$date_of_birth) / years(1))
parent$years_at_birth_f <- as.numeric(interval(parent$date_of_birth_f, parent$date_of_birth) / years(1))

#########################################################################

## MERGING FAMILY RELATIONS AND EA PGI

# Nuclear family PGIs by merging by id
within_fam_ea_pgi <- merge(parent, ea_pgi, by.x = "id", by.y = "project_pseudo_id")

within_fam_ea_pgi <- within_fam_ea_pgi %>%
  rename(
    # EA4 variables
    ea4_pgi = EA4_Meta_PGI,
    ea4_pgi_m = EA4_Meta_Mother_PGI,
    ea4_pgi_m_imp = EA4_Meta_Mother_PGI_Imp,
    ea4_pgi_f = EA4_Meta_Father_PGI,
    ea4_pgi_f_imp = EA4_Meta_Father_PGI_Imp,
    ea4_pgi_sum = EA4_Meta_PGI_Parental,
    
    # EA3 Noncog variables
    ea3noncog_pgi = EA3NonCog_PGI,
    ea3noncog_pgi_m = EA3NonCog_Mother_PGI,
    ea3noncog_pgi_m_imp = EA3NonCog_Mother_PGI_Imp,
    ea3noncog_pgi_f = EA3NonCog_Father_PGI,
    ea3noncog_pgi_f_imp = EA3NonCog_Father_PGI_Imp,
    ea3noncog_pgi_sum = EA3NonCog_PGI_Parental,

    # EA3 Cog variables
    ea3cog_pgi = EA3Cog_PGI,
    ea3cog_pgi_m = EA3Cog_Mother_PGI,
    ea3cog_pgi_m_imp = EA3Cog_Mother_PGI_Imp,
    ea3cog_pgi_f = EA3Cog_Father_PGI,
    ea3cog_pgi_f_imp = EA3Cog_Father_PGI_Imp,
    ea3cog_pgi_sum = EA3Cog_PGI_Parental,

    # PCs
    pc1 = PC1,
    pc2 = PC2,
    pc3 = PC3,
    pc4 = PC4,
    pc5 = PC5,
    pc6 = PC6,
    pc7 = PC7,
    pc8 = PC8,
    pc9 = PC9,
    pc10 = PC10
  )

# Print the number of rows
print(nrow(within_fam_ea_pgi)) #80090

#######################################################################

# Final selection of variables including PC variables at the end
within_fam_ea_pgi <- within_fam_ea_pgi %>%
  select(
    # IDs
    id, mom_id, dad_id,
    
    # Demographics and family info
    GENDER1M2F, fam_id, partner_id, 
    date_of_birth, year_of_birth, month_of_birth, date_of_inclusion,
    date_of_birth_m, year_of_birth_m, month_of_birth_m, n_child_m, years_at_birth_m,
    date_of_birth_f, year_of_birth_f, month_of_birth_f, n_child_f, years_at_birth_f,

    # EA4/EA3 Polygenic Indices
    ea4_pgi, ea4_pgi_m, ea4_pgi_f, ea4_pgi_m_imp, ea4_pgi_f_imp, ea4_pgi_sum,
    ea3noncog_pgi, ea3noncog_pgi_m, ea3noncog_pgi_f, ea3noncog_pgi_m_imp, ea3noncog_pgi_f_imp, ea3noncog_pgi_sum,
	ea3cog_pgi, ea3cog_pgi_m, ea3cog_pgi_f, ea3cog_pgi_m_imp, ea3cog_pgi_f_imp, ea3cog_pgi_sum,

	# PCs
	pc1, pc2, pc3, pc4, pc5, pc6, pc7, pc8, pc9, pc10)
	
# Save data frame
write.table(within_fam_ea_pgi,"/groups/umcg-lifelines/tmp01/projects/ov21_0226/lalajaasko/dfs/within_fam_ea_pgi.csv",
	sep=",",row.names=FALSE,quote=FALSE)

#######################################################################

# SAMPLE SIZES WITH GENETIC INFORMATION

# Total number of trios
print(sum(complete.cases(within_fam_ea_pgi[, c("ea4_pgi","ea4_pgi_m","ea4_pgi_f")]))) #3258
# Total number of trios including imputed values
print(sum(complete.cases(within_fam_ea_pgi[, c("ea4_pgi","ea4_pgi_sum")]))) #38908

#######################################################################

# END