#########################################################################
# Date: September 2024													
# Description: Code to set up PGI data and merge it with family relations
#########################################################################

module load R/4.2.2-foss-2022a-bare
R
library(dplyr)
library(data.table)

#######################################################################

## IMPORT RELEVANT DATASETS

# ea_pgi from LifelinesPGIFile_sbayesV2 as generated by Sjoerd
ea_pgi <- fread("/groups/umcg-lifelines/tmp01/projects/ov21_0226/PGSpipelineV2/OUTPUT/LifelinesPGIFile_sbayesV2.csv", 
	sep=",", header=TRUE)
ea_pgi <- as.data.frame(ea_pgi)

print(nrow(ea_pgi)) #167781

# Select relevant variables and rename
ea_pgi <- ea_pgi %>%
	select(project_pseudo_id, EA4_Meta_PGI,
	EA4_Meta_Mother_PGI, EA4_Meta_Mother_PGI_Imp, EA4_Meta_Father_PGI, EA4_Meta_Father_PGI_Imp, 
	EA4_Meta_PGI_Parental,
	EA3NonCog_PGI, EA3Cog_PGI, 
	EA3NonCog_Mother_PGI, EA3NonCog_Mother_PGI_Imp, EA3NonCog_Father_PGI, EA3NonCog_Father_PGI_Imp, 
	EA3Cog_Mother_PGI, EA3Cog_Mother_PGI_Imp, EA3Cog_Father_PGI, EA3Cog_Father_PGI_Imp,
	EA3NonCog_PGI_Parental, EA3Cog_PGI_Parental,
	PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10)
	
# Family relations dataset gparent
gparent <- fread("/groups/umcg-lifelines/tmp01/projects/ov21_0226/lalajaasko/dfs/gparent.csv",
	sep=",", header=TRUE)
gparent <- as.data.frame(gparent)

print(nrow(gparent)) #80090

#######################################################################

## MERGING FAMILY RELATIONS AND EA PGI

# Nuclear family PGIs by merging by id
within_fam_ea_pgi <- merge(gparent, ea_pgi, by.x = "id", by.y = "project_pseudo_id")

within_fam_ea_pgi <- within_fam_ea_pgi %>%
  rename(
    # EA4 variables
    ea4_pgi = EA4_Meta_PGI,
    ea4_pgi_m = EA4_Meta_Mother_PGI,
    ea4_pgi_m_imp = EA4_Meta_Mother_PGI_Imp,
    ea4_pgi_f = EA4_Meta_Father_PGI,
    ea4_pgi_f_imp = EA4_Meta_Father_PGI_Imp,
    ea4_pgi_sum = EA4_Meta_PGI_Parental,
    
    # EA3 Noncog variables
    ea3noncog_pgi = EA3NonCog_PGI,
    ea3noncog_pgi_m = EA3NonCog_Mother_PGI,
    ea3noncog_pgi_m_imp = EA3NonCog_Mother_PGI_Imp,
    ea3noncog_pgi_f = EA3NonCog_Father_PGI,
    ea3noncog_pgi_f_imp = EA3NonCog_Father_PGI_Imp,
    ea3noncog_pgi_sum = EA3NonCog_PGI_Parental,

    # EA3 Cog variables
    ea3cog_pgi = EA3Cog_PGI,
    ea3cog_pgi_m = EA3Cog_Mother_PGI,
    ea3cog_pgi_m_imp = EA3Cog_Mother_PGI_Imp,
    ea3cog_pgi_f = EA3Cog_Father_PGI,
    ea3cog_pgi_f_imp = EA3Cog_Father_PGI_Imp,
    ea3cog_pgi_sum = EA3Cog_PGI_Parental,

    # PCs
    pc1 = PC1,
    pc2 = PC2,
    pc3 = PC3,
    pc4 = PC4,
    pc5 = PC5,
    pc6 = PC6,
    pc7 = PC7,
    pc8 = PC8,
    pc9 = PC9,
    pc10 = PC10
  )

# Extended family with mother as focal parent by merging by mom_id
within_fam_ea_pgi <- merge(within_fam_ea_pgi, ea_pgi, by.x = "mom_id", by.y = "project_pseudo_id", all.x = TRUE)

within_fam_ea_pgi <- within_fam_ea_pgi %>%
  select(-EA4_Meta_PGI, -EA3NonCog_PGI, -EA3Cog_PGI,
  -PC1, -PC2, -PC3, -PC4, -PC5, -PC6, -PC7, -PC8, -PC9, -PC10) %>% 
  rename(
    # EA4 variables for maternal grandparents
    ea4_pgi_gmom_m = EA4_Meta_Mother_PGI,
    ea4_pgi_gmom_m_imp = EA4_Meta_Mother_PGI_Imp,
    ea4_pgi_gdad_m = EA4_Meta_Father_PGI,
    ea4_pgi_gdad_m_imp = EA4_Meta_Father_PGI_Imp,
    ea4_pgi_sum_m = EA4_Meta_PGI_Parental,

    # EA3 Noncog PGI variables for maternal grandparents
    ea3noncog_pgi_gmom_m = EA3NonCog_Mother_PGI,
    ea3noncog_pgi_gmom_m_imp = EA3NonCog_Mother_PGI_Imp,
    ea3noncog_pgi_gdad_m = EA3NonCog_Father_PGI,
    ea3noncog_pgi_gdad_m_imp = EA3NonCog_Father_PGI_Imp,
    ea3noncog_pgi_sum_m = EA3NonCog_PGI_Parental,

    # EA3 Cog PGI variables for maternal grandparents
    ea3cog_pgi_gmom_m = EA3Cog_Mother_PGI,
    ea3cog_pgi_gmom_m_imp = EA3Cog_Mother_PGI_Imp,
    ea3cog_pgi_gdad_m = EA3Cog_Father_PGI,
    ea3cog_pgi_gdad_m_imp = EA3Cog_Father_PGI_Imp,
    ea3cog_pgi_sum_m = EA3Cog_PGI_Parental
  )

# Extended family with father as focal parent by merging by dad_id
within_fam_ea_pgi <- merge(within_fam_ea_pgi, ea_pgi, by.x = "dad_id", by.y = "project_pseudo_id", all.x = TRUE)

within_fam_ea_pgi <- within_fam_ea_pgi %>%
  select(-EA4_Meta_PGI, -EA3NonCog_PGI, -EA3Cog_PGI,
  -PC1, -PC2, -PC3, -PC4, -PC5, -PC6, -PC7, -PC8, -PC9, -PC10) %>%
  rename(
    # EA4 variables for paternal grandparents
    ea4_pgi_gmom_f = EA4_Meta_Mother_PGI,
    ea4_pgi_gmom_f_imp = EA4_Meta_Mother_PGI_Imp,
    ea4_pgi_gdad_f = EA4_Meta_Father_PGI,
    ea4_pgi_gdad_f_imp = EA4_Meta_Father_PGI_Imp,
    ea4_pgi_sum_f = EA4_Meta_PGI_Parental,

    # EA3 Noncog PGI variables for paternal grandparents
    ea3noncog_pgi_gmom_f = EA3NonCog_Mother_PGI,
    ea3noncog_pgi_gmom_f_imp = EA3NonCog_Mother_PGI_Imp,
    ea3noncog_pgi_gdad_f = EA3NonCog_Father_PGI,
    ea3noncog_pgi_gdad_f_imp = EA3NonCog_Father_PGI_Imp,
    ea3noncog_pgi_sum_f = EA3NonCog_PGI_Parental,

    # EA3 Cog PGI variables for paternal grandparents
    ea3cog_pgi_gmom_f = EA3Cog_Mother_PGI,
    ea3cog_pgi_gmom_f_imp = EA3Cog_Mother_PGI_Imp,
    ea3cog_pgi_gdad_f = EA3Cog_Father_PGI,
    ea3cog_pgi_gdad_f_imp = EA3Cog_Father_PGI_Imp,
    ea3cog_pgi_sum_f = EA3Cog_PGI_Parental
  )

# Print the number of rows
print(nrow(within_fam_ea_pgi)) #80090

#######################################################################

## GENERATE FOCAL PGI VARIABLES FOR PEDIGREE ANALYSES

# Generalized function to create focal, non-focal, and gender-neutral PGI variables including imputed values for non-focal PGIs
create_focal_pgi <- function(data, pgi_type, pgi_m, pgi_m_imp, pgi_f, pgi_f_imp, pgi_sum_m, pgi_sum_f) {
  
  data <- data %>%
    mutate(
      # Mother is considered a focal parent if both her PGI and maternal grandparental PGI are present
      !!paste0(pgi_type, "_pgi_m_focal") := if_else(!is.na(!!sym(pgi_m)) & !is.na(!!sym(pgi_sum_m)), !!sym(pgi_m), NA_real_),
      !!paste0(pgi_type, "_pgi_sum_m_focal") := if_else(!is.na(!!sym(pgi_m)) & !is.na(!!sym(pgi_sum_m)), !!sym(pgi_sum_m), NA_real_),
      
      # Father is considered a focal parent if both his PGI and paternal grandparental PGI are present
      !!paste0(pgi_type, "_pgi_f_focal") := if_else(!is.na(!!sym(pgi_f)) & !is.na(!!sym(pgi_sum_f)), !!sym(pgi_f), NA_real_),
      !!paste0(pgi_type, "_pgi_sum_f_focal") := if_else(!is.na(!!sym(pgi_f)) & !is.na(!!sym(pgi_sum_f)), !!sym(pgi_sum_f), NA_real_),
      
      # If the mother is focal, father becomes non-focal, using imputed if available
      !!paste0(pgi_type, "_pgi_f_nonfocal") := if_else(!is.na(!!sym(pgi_m)) & !is.na(!!sym(pgi_sum_m)), 
                                                       coalesce(!!sym(pgi_f), !!sym(pgi_f_imp)), NA_real_),
      
      # If the father is focal, mother becomes non-focal, using imputed if available
      !!paste0(pgi_type, "_pgi_m_nonfocal") := if_else(!is.na(!!sym(pgi_f)) & !is.na(!!sym(pgi_sum_f)), 
                                                       coalesce(!!sym(pgi_m), !!sym(pgi_m_imp)), NA_real_),
      
      # Gender-neutral focal PGI: Either parent can be focal
      !!paste0(pgi_type, "_pgi_focal") := coalesce(!!sym(paste0(pgi_type, "_pgi_m_focal")), !!sym(paste0(pgi_type, "_pgi_f_focal"))),
      !!paste0(pgi_type, "_pgi_sum_focal") := coalesce(!!sym(paste0(pgi_type, "_pgi_sum_m_focal")), !!sym(paste0(pgi_type, "_pgi_sum_f_focal"))),
      
      # Gender-neutral non-focal PGI: The non-focal parent if the other parent is focal, using imputed if available
      !!paste0(pgi_type, "_pgi_nonfocal") := coalesce(!!sym(paste0(pgi_type, "_pgi_f_nonfocal")), !!sym(paste0(pgi_type, "_pgi_m_nonfocal")))
    )
  
  return(data)
}

# List of PGI types and their corresponding column names (including imputed PGIs)
pgi_info <- list(
  list(type = "ea4", pgi_m = "ea4_pgi_m", pgi_m_imp = "ea4_pgi_m_imp", pgi_f = "ea4_pgi_f", pgi_f_imp = "ea4_pgi_f_imp", pgi_sum_m = "ea4_pgi_sum_m", pgi_sum_f = "ea4_pgi_sum_f"),
  list(type = "ea3noncog", pgi_m = "ea3noncog_pgi_m", pgi_m_imp = "ea3noncog_pgi_m_imp", pgi_f = "ea3noncog_pgi_f", pgi_f_imp = "ea3noncog_pgi_f_imp", pgi_sum_m = "ea3noncog_pgi_sum_m", pgi_sum_f = "ea3noncog_pgi_sum_f"),
  list(type = "ea3cog", pgi_m = "ea3cog_pgi_m", pgi_m_imp = "ea3cog_pgi_m_imp", pgi_f = "ea3cog_pgi_f", pgi_f_imp = "ea3cog_pgi_f_imp", pgi_sum_m = "ea3cog_pgi_sum_m", pgi_sum_f = "ea3cog_pgi_sum_f")
)

# Apply the function for all PGI types using a loop
for (pgi in pgi_info) {
  within_fam_ea_pgi <- create_focal_pgi(within_fam_ea_pgi, pgi$type, pgi$pgi_m, pgi$pgi_m_imp, pgi$pgi_f, pgi$pgi_f_imp, pgi$pgi_sum_m, pgi$pgi_sum_f)
}

#######################################################################

# Final selection of variables including PC variables at the end
within_fam_ea_pgi <- within_fam_ea_pgi %>%
  select(
    # IDs
    id, mom_id, dad_id, gmom_id_m, gdad_id_m, gmom_id_f, gdad_id_f,
    
    # Demographics and family info
    GENDER1M2F, fam_id, partner_id, partner_id_m, partner_id_f,
    date_of_birth, year_of_birth, month_of_birth, date_of_inclusion,
    date_of_birth_m, year_of_birth_m, month_of_birth_m, n_child_m, years_at_birth_m,
    date_of_birth_f, year_of_birth_f, month_of_birth_f, n_child_f, years_at_birth_f,

    # EA4 Polygenic Indices
    ea4_pgi, ea4_pgi_m, ea4_pgi_f, ea4_pgi_m_imp, ea4_pgi_f_imp, ea4_pgi_sum,
    ea4_pgi_gmom_m, ea4_pgi_gdad_m, ea4_pgi_gmom_m_imp, ea4_pgi_gdad_m_imp, ea4_pgi_sum_m,
    ea4_pgi_gmom_f, ea4_pgi_gdad_f, ea4_pgi_gmom_f_imp, ea4_pgi_gdad_f_imp, ea4_pgi_sum_f,
	ea4_pgi_focal, ea4_pgi_sum_focal, ea4_pgi_nonfocal,
	ea4_pgi_m_focal, ea4_pgi_sum_m_focal, ea4_pgi_f_nonfocal,
	ea4_pgi_f_focal, ea4_pgi_sum_f_focal, ea4_pgi_m_nonfocal,

    # EA3 Noncog PGI Indices
    ea3noncog_pgi, ea3noncog_pgi_m, ea3noncog_pgi_f, ea3noncog_pgi_m_imp, ea3noncog_pgi_f_imp, ea3noncog_pgi_sum,
    ea3noncog_pgi_gmom_m, ea3noncog_pgi_gdad_m, ea3noncog_pgi_gmom_m_imp, ea3noncog_pgi_gdad_m_imp, ea3noncog_pgi_sum_m,
    ea3noncog_pgi_gmom_f, ea3noncog_pgi_gdad_f, ea3noncog_pgi_gmom_f_imp, ea3noncog_pgi_gdad_f_imp, ea3noncog_pgi_sum_f,
	ea3noncog_pgi_focal, ea3noncog_pgi_sum_focal, ea3noncog_pgi_nonfocal,
	ea3noncog_pgi_m_focal, ea3noncog_pgi_sum_m_focal, ea3noncog_pgi_f_nonfocal,
	ea3noncog_pgi_f_focal, ea3noncog_pgi_sum_f_focal, ea3noncog_pgi_m_nonfocal,
	
    # EA3 Cog PGI Indices
    ea3cog_pgi, ea3cog_pgi_m, ea3cog_pgi_f, ea3cog_pgi_m_imp, ea3cog_pgi_f_imp, ea3cog_pgi_sum,
    ea3cog_pgi_gmom_m, ea3cog_pgi_gdad_m, ea3cog_pgi_gmom_m_imp, ea3cog_pgi_gdad_m_imp, ea3cog_pgi_sum_m,
    ea3cog_pgi_gmom_f, ea3cog_pgi_gdad_f, ea3cog_pgi_gmom_f_imp, ea3cog_pgi_gdad_f_imp, ea3cog_pgi_sum_f,
	ea3cog_pgi_focal, ea3cog_pgi_sum_focal, ea3cog_pgi_nonfocal,
	ea3cog_pgi_m_focal, ea3cog_pgi_sum_m_focal, ea3cog_pgi_f_nonfocal,
	ea3cog_pgi_f_focal, ea3cog_pgi_sum_f_focal, ea3cog_pgi_m_nonfocal,

	# PCs
	pc1, pc2, pc3, pc4, pc5, pc6, pc7, pc8, pc9, pc10)
	
# Save data frame
write.table(within_fam_ea_pgi,"/groups/umcg-lifelines/tmp01/projects/ov21_0226/lalajaasko/dfs/within_fam_ea_pgi.csv",
	sep=",",row.names=FALSE,quote=FALSE)	

#######################################################################

## COUNTING SAMPLE SIZES

# EA4 PGI
	
# Count the number of triads with EA PGI info for both parents
n_triads_with_ea4_pgi <- within_fam_ea_pgi %>%
	filter(!is.na(mom_id) & !is.na(dad_id) &               # Both mom and dad are present
	(!is.na(ea4_pgi_m) | !is.na(ea4_pgi_m_imp)) &     # EA PGI available for mom (imputed or non-imputed)
	(!is.na(ea4_pgi_f) | !is.na(ea4_pgi_f_imp))) %>%  # EA PGI available for dad (imputed or non-imputed)
  nrow()

# Count the number of triads with EA3 Noncog and Cog PGI info for both parents
n_triads_with_ea3_pgi <- within_fam_ea_pgi %>%
  filter(!is.na(mom_id) & !is.na(dad_id) &                # Both mom and dad are present
         # EA3 Noncog PGI available for both mom and dad
         ((!is.na(ea3noncog_pgi_m) | !is.na(ea3noncog_pgi_m_imp)) & 
          (!is.na(ea3noncog_pgi_f) | !is.na(ea3noncog_pgi_f_imp))) &
         # EA3 Cog PGI available for both mom and dad
         ((!is.na(ea3cog_pgi_m) | !is.na(ea3cog_pgi_m_imp)) &
          (!is.na(ea3cog_pgi_f) | !is.na(ea3cog_pgi_f_imp)))) %>%
  nrow()

# Print result
print(n_triads_with_ea3_pgi) #31969
print(n_triads_with_ea4_pgi) #31969

# Count the number of extended families with EA PGI info for either set of grandparents
n_extended_families_with_ea4_pgi <- within_fam_ea_pgi %>%
  filter(
    # Check if both maternal grandparents are present and have EA PGI data
    (!is.na(gmom_id_m) & !is.na(gdad_id_m) &     
     (!is.na(ea4_pgi_gmom_m) | !is.na(ea4_pgi_gmom_m_imp)) &  
     (!is.na(ea4_pgi_gdad_m) | !is.na(ea4_pgi_gdad_m_imp))) |
    
    # Check if both paternal grandparents are present and have EA PGI data
    (!is.na(gmom_id_f) & !is.na(gdad_id_f) &     
     (!is.na(ea4_pgi_gmom_f) | !is.na(ea4_pgi_gmom_f_imp)) &  
     (!is.na(ea4_pgi_gdad_f) | !is.na(ea4_pgi_gdad_f_imp)))
  ) %>%
  nrow()

# Count the number of extended families with EA3 Noncog and Cog PGI info for either set of grandparents
n_extended_families_with_ea3_pgi <- within_fam_ea_pgi %>%
  filter(
    # Check if both maternal grandparents are present and have EA3 PGI data
    (!is.na(gmom_id_m) & !is.na(gdad_id_m) &     
     ((!is.na(ea3noncog_pgi_gmom_m) | !is.na(ea3noncog_pgi_gmom_m_imp)) &  
      (!is.na(ea3noncog_pgi_gdad_m) | !is.na(ea3noncog_pgi_gdad_m_imp))) &
     ((!is.na(ea3cog_pgi_gmom_m) | !is.na(ea3cog_pgi_gmom_m_imp)) &  
      (!is.na(ea3cog_pgi_gdad_m) | !is.na(ea3cog_pgi_gdad_m_imp)))) |
    
    # Check if both paternal grandparents are present and have EA3 PGI data
    (!is.na(gmom_id_f) & !is.na(gdad_id_f) &     
     ((!is.na(ea3noncog_pgi_gmom_f) | !is.na(ea3noncog_pgi_gmom_f_imp)) &  
      (!is.na(ea3noncog_pgi_gdad_f) | !is.na(ea3noncog_pgi_gdad_f_imp))) &
     ((!is.na(ea3cog_pgi_gmom_f) | !is.na(ea3cog_pgi_gmom_f_imp)) &  
      (!is.na(ea3cog_pgi_gdad_f) | !is.na(ea3cog_pgi_gdad_f_imp))))
  ) %>%
  nrow()

# Print result
print(n_extended_families_with_ea3_pgi) #9549
print(n_extended_families_with_ea4_pgi) #9549

#######################################################################

# SAMPLE SIZES WITH GENETIC INFORMATION

# Total number of trios
print(sum(complete.cases(within_fam_ea_pgi[, c("ea4_pgi","ea4_pgi_m","ea4_pgi_f")]))) #3174
# Total number of trios including imputed values
print(sum(complete.cases(within_fam_ea_pgi[, c("ea4_pgi","ea4_pgi_sum")]))) #31969

# Total number of extended pedigree families focusing on mothers
print(sum(complete.cases(within_fam_ea_pgi[, c("ea4_pgi","ea4_pgi_m","ea4_pgi_sum","ea4_pgi_sum_m")]))) #2454
# Total number of extended pedigree families focusing on fathers
print(sum(complete.cases(within_fam_ea_pgi[, c("ea4_pgi","ea4_pgi_f","ea4_pgi_sum","ea4_pgi_sum_f")]))) #1599

# Count unique ID values where a focal parent (mother or father) is observed for any PGI type
num_unique_ids_focal <- within_fam_ea_pgi %>%
  filter(!is.na(ea4_pgi_m_focal) | !is.na(ea4_pgi_f_focal) | 
         !is.na(ea3noncog_pgi_m_focal) | !is.na(ea3noncog_pgi_f_focal) |
         !is.na(ea3cog_pgi_m_focal) | !is.na(ea3cog_pgi_f_focal)) %>%
  summarise(num_unique_ids = n_distinct(id))
num_unique_ids_focal #3729

# Get the list of individuals with focal mothers
focal_mothers <- within_fam_ea_pgi %>%
  filter(complete.cases(ea4_pgi, ea4_pgi_m, ea4_pgi_sum, ea4_pgi_sum_m)) %>%
  select(id)

# Get the list of individuals with focal fathers
focal_fathers <- within_fam_ea_pgi %>%
  filter(complete.cases(ea4_pgi, ea4_pgi_f, ea4_pgi_sum, ea4_pgi_sum_f)) %>%
  select(id)

# Find the number of overlapping individuals (present in both sets)
overlapping_ids <- focal_mothers %>%
  inner_join(focal_fathers, by = "id") %>%
  n_distinct()
print(overlapping_ids) #324

print(2454+1599-324) #3729

#######################################################################

# END